# Generated by Django 5.1.5 on 2025-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_date_de_publicatio_article_date_de_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments_ids',
            field=models.ManyToManyField(related_name='comment_article_ids', to='blog.commentaire', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_de_publication',
            field=models.DateField(auto_now_add=True),
        ),
    ]
