# Generated by Django 5.1.5 on 2025-02-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_commentaire_options_commentaire_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='article',
            name='comments_ids',
        ),
        migrations.AddField(
            model_name='article',
            name='comments_ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_article_ids', to='blog.commentaire', verbose_name='Comment'),
        ),
    ]
