# Generated by Django 5.1.5 on 2025-02-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_commentaire_likes_remove_commentaire_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments_ids',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
