# Generated by Django 5.1.5 on 2025-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_de_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
